### ISSUE TITLE
没有formData 参数

### ISSUE THREAD

**Issue by zwd862375698** [simple-uploader/Uploader#104]
我在上传大一点的文件 并且chunkSize 设置为1 * 1024 * 1024 * 1024的时候，请求参数里没有携带任何上传的参数，在我上传几KB的小文件的时候就携带了

**Comment by zwd862375698** [comment]
![image](https://user-images.githubusercontent.com/23628047/116550756-b9bf3000-a929-11eb-8207-e99c773a9a68.png)

**Comment by zwd862375698** [comment]
![Uploading image.png…]()

**Comment by zwd862375698** [comment]
![image](https://user-images.githubusercontent.com/23628047/116550855-d196b400-a929-11eb-99d3-869ccfbcc91c.png)

**Comment by dolymood** [comment]
这个只是浏览器预览的策略 并不是没有
