### ISSUE TITLE
checkChunkUploadedByResponse后端返回值接收不到

### ISSUE THREAD

**Issue by Ibyboy** [simple-uploader/Uploader#107]
![image](https://user-images.githubusercontent.com/42126940/117590835-e104d100-b163-11eb-945e-411f83ad4285.png)

![image](https://user-images.githubusercontent.com/42126940/117590866-0abdf800-b164-11eb-866e-8adca8019b0f.png)

当testChunks=true时，后端传来的uploaded值会丢失，为false这些值正常。

**Comment by dolymood** [comment]
应该不会，可以debug下 看在成功回调中 得到的原始值是啥

**Comment by Ibyboy** [comment]
技术尚浅，组件封装的很深，跟进去看了没查找到原因，不知道在哪步丢了值。
项目地址：https://github.com/Ibyboy/ddisk-web，remote_serve分支可以直接连接远程服务器，组件路径/src/components/GlobalUploader.vue。
如果您有空的话可以看一下吗？后端逻辑应该没问题，要不然testChunks也不会能获取到值。

**Comment by dolymood** [comment]
看了下 ，那个时候 get 请求后端返回的 uploaded确实是 null，所以数据没问题 是后端接口有问题

**Comment by Ibyboy** [comment]
真正切片上传时，post返回丢值了。
