### ISSUE TITLE
Wrong fact in the documentation

### ISSUE THREAD

**Issue by akarelas** [simple-uploader/Uploader#118]
In https://github.com/simple-uploader/Uploader#how-do-i-set-it-up-with-my-server, at `chunkSize`, it says "the size of the data received in the HTTP might be lower than chunkSize of this for the last chunk for a file." but the reality is the size of the data received in the last chunk can be **greater** (not lower) than chunkSize (by default setting of `forceChunkSize`).

**Comment by dolymood** [comment]
Thanks
