### ISSUE TITLE
文件上传个数限制

### ISSUE THREAD

**Issue by Hollelihanqi** [simple-uploader/Uploader#127]
如何限制每次只能选择一个文件，而不是多个同时上传？

**Comment by dolymood** [comment]
如果是选择 参考https://github.com/simple-uploader/Uploader/blob/develop/README_zh-CN.md#%E6%96%B9%E6%B3%95 assignBrowse
如果是控制文件上传，现在默认只上传一个文件，只是分多块并发上传，除非是上一个文件已经基本传完 才会传下一个文件的开始的块
