### ISSUE TITLE
重试会发送多个请求

### ISSUE THREAD

**Issue by jiangqiang1996** [simple-uploader/Uploader#134]
文件分片上传，分片上传成功了，但是合并分片失败，此时触发重试事件，如果分片还是上传成功，会触发多次filesuccess事件。

比如一个文件分成五片，每一片都能上传成功，但是合并接口出了问题，合并失败了，此时点击重试按钮，每一片又都成功了，然后就会触发5次filesuccess事件。

**Comment by dolymood** [comment]
这符合预期，还是看你自己自定义实现
对于uploader没有单独的合并接口逻辑

**Comment by mofiter** [comment]
> 文件分片上传，分片上传成功了，但是合并分片失败，此时触发重试事件，如果分片还是上传成功，会触发多次filesuccess事件。
> 
> 比如一个文件分成五片，每一片都能上传成功，但是合并接口出了问题，合并失败了，此时点击重试按钮，每一片又都成功了，然后就会触发5次filesuccess事件。

兄弟你合并分片的请求是在哪里写的啊

**Comment by jiangqiang1996** [comment]
> > 文件分片上传，分片上传成功了，但是合并分片失败，此时触发重试事件，如果分片还是上传成功，会触发多次filesuccess事件。
> > 比如一个文件分成五片，每一片都能上传成功，但是合并接口出了问题，合并失败了，此时点击重试按钮，每一片又都成功了，然后就会触发5次filesuccess事件。
> 
> 兄弟你合并分片的请求是在哪里写的啊

文件上传成功的回调里面写的
