### ISSUE TITLE
不上传文件

### ISSUE THREAD

**Issue by nnlaksdf** [simple-uploader/Uploader#139]
只有get 预检请求，没有后面post 真实请求。
![image](https://user-images.githubusercontent.com/44264911/188783136-fc2d6e9a-b938-4cac-b51a-0b5a6edc2efc.png)
![image](https://user-images.githubusercontent.com/44264911/188783169-62cf8641-f15e-42eb-bc45-9f2c17893fe0.png)

**Comment by dolymood** [comment]
看文档，根据状态码决定
