### ISSUE TITLE
哥们有考虑过增加beforeupload的事件吗？

### ISSUE THREAD

**Issue by hasbug** [simple-uploader/Uploader#14]
最近搞上传头大，图片的旋转问题。
如果有beforeupload的话，能够自己进行图片旋转后再上传就好了

**Comment by dolymood** [comment]
如果你处理图片旋转是同步的，可以使用 initFileFn 配置项

**Comment by houzw** [comment]
有时候需要在上传之前做表单的验证，应该怎么处理？
