### ISSUE TITLE
断网如何续传？

### ISSUE THREAD

**Issue by ramseyfeng** [simple-uploader/Uploader#142]
目前看着暂停是支持续传的，想知道断网为啥只能重传而不能续传?
有个场景就是网络不稳定，传个比较大的文件好几个G那种，网络突然中断，想问如何能够支持续传？前端看着resume是不显示已经，请问有啥办法

**Comment by dolymood** [comment]
续传 靠服务端
核心还是check哪些块不需要上传，这样就实现续传效果

**Comment by ramseyfeng** [comment]
感谢回答已理解
