### ISSUE TITLE
请教如何自定义控制上传进度条百分比

### ISSUE THREAD

**Issue by rysinal** [simple-uploader/Uploader#155]
有个自定义需求请教下：
 不知道有没有方法可以控制进度背景条的展示百分比，比如50%的实际上传进度在上传的list里手动控制展示为25%的进度条长度（上传完有异步任务处理，这部分的进度会手动加），由自定义代码和接口来设置这个进度条是否到100%

**Comment by dolymood** [comment]
进度条还是按照上传进度来的，要不然就乱套了
