### ISSUE TITLE
请问能否在上传时，单独处理query参数，query的参数为异步获取

### ISSUE THREAD

**Issue by haiting** [simple-uploader/Uploader#158]
如果query的参数，需要通过API获取回来，该在哪里触发异步操作？
在onFileAdded触发获取API的参数，然后复制给变量 query，在query函数里面再组装数据，貌似会有异步延迟
<img width="794" alt="image" src="https://github.com/simple-uploader/Uploader/assets/20320396/2b1140e5-17f3-40de-aa6f-529493153738">

<img width="757" alt="image" src="https://github.com/simple-uploader/Uploader/assets/20320396/3ed7edd1-3ce2-4e90-8174-525315d69568">

_Originally posted by @haiting in https://github.com/simple-uploader/Uploader/issues/20#issuecomment-1713653421_
            
            
          比如同时上传两个视频， 触发分片上传后，参数只其中一个视频的上传是带uploadId的

**Comment by dolymood** [comment]
可以考虑利用 preprocess preprocessFinished 处理

**Comment by 1010830256** [comment]
实测出来的结果是这样的：
快速的分2次上传2个文件(不是一次性多选2个文件)，第一个文件先执行了added回掉，然后由added中调用的file.resume()来触发文件上传，这样子第一个文件的上传请求中是包含了uploadId的，然后第二个文件，会自动上传，而不是执行added中的file.resume()来触发的上传
