### ISSUE TITLE
processResponse 如何取消文件上传

### ISSUE THREAD

**Issue by hasbug** [simple-uploader/Uploader#17]
场景：文件分块上传。
根据后端返回状态码的不同，需要在processResponse 进行处理，例如，返回一个400，那么我需要提示用户，并删除这个出问题的文件（rootfile），但在processResponse 中如何取得对应的rootfile呢？

如果我能知道当前这个状态对应的rootfile 我就能用cacel进行取消上传···

**Comment by dolymood** [comment]
如果认为是错误的case，可以直接在错误事件中处理就可以了吧，例如 fileError 事件。

如果一定是在 processResponse 中处理，那处理结果会直接影响派发的事件，也是依旧可以在 fileError 事件中处理的。

**Comment by ramseyfeng** [comment]
@hasbug @dolymood 请问这个processResponse如何取消上传？ throw new Error()?
