### ISSUE TITLE
请问能否在上传时，单独处理query参数？！

### ISSUE THREAD

**Issue by yzdel200** [simple-uploader/Uploader#20]
目录上传，如果目录有子目录和文件，在filesSubmitted事件处理子目录的服务器创建，然后文件上传需要加上query参数写入目录的id.可是现在的query是全局的，没办法在文件上传前就把这个query参数修改掉，即使修改了，多文件同时上传的时候，也会造成query参数在其他文件上传的时候被覆盖掉。
能否把query参数写在fileList的每个file里面，上传的时候直接使用每个file自己的query.

**Comment by dolymood** [comment]
query 可以是函数的

**Comment by haiting** [comment]
> query 可以是函数的

如果query的参数，需要通过API获取回来，改在哪里触发？在onFileAdded触发获取API的参数，然后复制给变量 query，在query函数里面再组装数据，貌似会有异步延迟
<img width="794" alt="image" src="https://github.com/simple-uploader/Uploader/assets/20320396/2b1140e5-17f3-40de-aa6f-529493153738">

<img width="757" alt="image" src="https://github.com/simple-uploader/Uploader/assets/20320396/3ed7edd1-3ce2-4e90-8174-525315d69568">
