### ISSUE TITLE
后端需要怎么拼文件

### ISSUE THREAD

**Issue by ccsmily** [simple-uploader/Uploader#29]
后端收到所有文件片段后要怎么拼文件？

**Comment by dolymood** [comment]
参考 https://github.com/23/resumable.js/tree/master/samples 

都是类似的

**Comment by fjh1997** [comment]
直接通过GET /download/:identifier 下载就可以了。

**Comment by anyanhui** [comment]
直接调用GET /download/:identifier，我没有成功，增加了一个filename的字段，同时自定义了一个var stream = fs.createWriteStream(filename)；再sourceStream.pipe(stream, {
            end: false
          });
才成功的

针对示例的有成功的吗
