### ISSUE TITLE
请问可以在上传前获取到接口的分块等参数吗？

### ISSUE THREAD

**Issue by 364124337** [simple-uploader/Uploader#33]
因为上传前需要掉一个初始化的接口（这里需要传入分块等参数）然后再调取上传的接口。

**Comment by dolymood** [comment]
preprocess 配置项？完成后调用 块实例的 preprocessFinished 即可

**Comment by 364124337** [comment]
嗯，我还想问下怎么上传同一个文件？因为我在filesAdded里面使用cancel移除了，但是重新上传同一个文件，文件数组显示为空

**Comment by 364124337** [comment]
如果是编辑页面，怎么显示已经上传的文件？
