### ISSUE TITLE
如果能够控制每次分片上传的opts参数，将能提供更大的灵活性。

### ISSUE THREAD

**Issue by cqkd6381** [simple-uploader/Uploader#43]
公司有一个业务，上传分三步：
①根据文件大小申请分片上传地址和具体分片参数
②将文件分片并上传到对应的地址
③发送请求完成通知
如果能够在每次分片上传的时候能够控制uploader.opts的target参数（或更多参数），将能提供更大的灵活性。

**Comment by dolymood** [comment]
target是函数 就可以满足需求了吧？
