### ISSUE TITLE
额外需要传入的参数不起作用

### ISSUE THREAD

**Issue by zhangjing007** [simple-uploader/Uploader#58]
![image](https://user-images.githubusercontent.com/24825020/70770291-c0d2b600-1da7-11ea-8b58-f027ff1dcefe.png)

![image](https://user-images.githubusercontent.com/24825020/70770296-c6c89700-1da7-11ea-9f63-f827fb4e7f74.png)

**Comment by dolymood** [comment]
options 中增加query肯定是可以用的 一实验

**Comment by 1010830256** [comment]
query是一个Function，而不是Object，你应该写成
```javascript
query: () => {
    return {
        clientId: '111',
        clientSecret: 'xxxx',
    }
}
```
