### ISSUE TITLE
请问大佬怎么实现手动上传啊？

### ISSUE THREAD

**Issue by peewee922** [simple-uploader/Uploader#60]
我的需求是点击“”上传“”按钮加入上传任务，然后表单中其他字段填写好后，点击“提交“按钮才开始上传。

**Comment by dolymood** [comment]
提交开始上传 就是默认不上传 然后走上传就好了 有配置项， 以及此时的上传应该调用 resume 方法

**Comment by colorfulyang** [comment]
> 提交开始上传 就是默认不上传 然后走上传就好了 有配置项， 以及此时的上传应该调用 resume 方法

我也是手动提交，调用resume方法，问题是提交了一次再次提交就不会触发上传了，options参数里边allowDuplicatedUploads也设置了true,这是什么问题啊，我想要多次提交。。
