### ISSUE TITLE
上传多个文件的问题

### ISSUE THREAD

**Issue by zahdxj** [simple-uploader/Uploader#64]
同时选中了两个文件，为什么先上传了部分文件B，然后暂停了转去上传文件A了，A传完之后又来传B了，有什么办法能让一个个的传么？并发个数simultaneousUploads已经设置成1了

**Comment by dolymood** [comment]
这个行为不应该是对的吗
这就是一个个传的 
你说的暂停了 改去传其他的 一定是 请求发生了问题 导致暂停 不可能莫名暂停的

**Comment by zahdxj** [comment]
关键是并发数我设置成了1啊

**Comment by dolymood** [comment]
建议提供示例demo 才可以

**Comment by zhangdanna** [comment]
怎么去掉alert确认弹窗呢

**Comment by luqiudi** [comment]
我并发上传数设置为3,还是一个个传呀,作者
