### ISSUE TITLE
怎么改变或者获知文件的上传状态。

### ISSUE THREAD

**Issue by nathon-wang** [simple-uploader/Uploader#7]
我的需求是这样的，文件上传到服务器之后还要进行处理，只有处理完才能算上传完。所以进度条100%时我想显示文件处理中...提示用户文件还没上传完。通过file-progress事件，发现没有一个表示现在具体进度或者状态的字段，问下这个改怎么处理，谢谢。

**Comment by dolymood** [comment]
这个可能只有新增加状态才可以控制了，目前的话 应该不大好做

**Comment by dolymood** [comment]
0.3 新增了配置项

* `processResponse` 处理请求结果，默认 `function (response, cb) { cb(null, response) }`.
