### ISSUE TITLE
simple-uploader源码出错

### ISSUE THREAD

**Issue by GodLyons** [simple-uploader/Uploader#70]
运行环境：vuecli，在使用simple-uploader的时候，发现报错，后来排查源码发现在`this.xhr.upload.addEventListener`这句代码中应该改为`this.xhr.addEventListener`，我修改后程序正常运行。

**Comment by starsonic** [comment]
` this.xhr.upload.addEventListener('progress', progressHandler, false)`
上传触发的是xhr.upload对象的 onprogress事件，下载才会触发的是xhr对象的onprogress事件

**Comment by GodLyons** [comment]
我并没有读源码，大概一个月前我使用的使用发现引入之后代码报错，去看了看代码，然后删除掉.upload后程序运行正常，其他功能也正常运行。

**Comment by dolymood** [comment]
之前报错大概率是因为mockjs 并不支持 upload
也有相关issue讨论
