### ISSUE TITLE
this is undefined when exec uploader.opts.processResponse

### ISSUE THREAD

**Issue by frankggyy** [simple-uploader/Uploader#79]
![image](https://user-images.githubusercontent.com/234368/90608730-99d15b80-e235-11ea-8d0a-5566091408ad.png)

occurred after packaged with webpack

**Comment by yuleiQ** [comment]
我也遇见了这个问题 this走进去是undefined

**Comment by yuleiQ** [comment]
@dolymood 请问作者大大什么时候上传一个npm包啊 我的包版本是0.5.4仍旧存在此问题

**Comment by frankggyy** [comment]
@dolymood Great job👍👍👍

**Comment by dolymood** [comment]
0.5.5 fixed
