### ISSUE TITLE
上传文件每次都只执行checkChunk 而没有执行uploadChunk。

### ISSUE THREAD

**Issue by 15773200610** [simple-uploader/Uploader#83]
上传文件每次都只执行checkChunk 而没有执行uploadChunk。请教大佬们，如何调用到这个方法，或者调用时机是哪个方法

**Comment by dolymood** [comment]
check的逻辑是走到了指定的状态 才会认为是 需要上传的

**Comment by 15773200610** [comment]
能否问一下是哪个状态？

**Comment by 15773200610** [comment]
> check的逻辑是走到了指定的状态 才会认为是 需要上传的
能否指教一下，这步具体在哪个方法或函数里面实现的？
