### ISSUE TITLE
IE11和火狐浏览器内存泄漏问题

### ISSUE THREAD

**Issue by yinyukang-cuc** [simple-uploader/Uploader#84]
1.IE11浏览器和火狐浏览器文件分片上传，内存持续增加，文件上传完成成后，调用了uploader.cancel()，内存也不释放。插件代码里使用了循环引用，不知道是否有关系。
2.目前IE浏览器内存达到1.5G左右，会自动刷新。

**Comment by dolymood** [comment]
拿官方例子 看 chrome memory 工具 貌似看不出内存泄漏

**Comment by yinyukang-cuc** [comment]
@dolymood 可以用IE11检测，F12->内存->开始分析会话

**Comment by yinyukang-cuc** [comment]
![image](https://user-images.githubusercontent.com/51773762/92583067-629a1b80-f2c4-11ea-88d4-1e804a2c7ccc.png)
这是官方提供的样例，内存泄漏相对还好。我这边情况会更糟糕一些

**Comment by yinyukang-cuc** [comment]
![image](https://user-images.githubusercontent.com/51773762/92591482-90855d00-f2d0-11ea-8eb0-0a6f6527ccfb.png)
我上传了一个2G文件，内存增加了300多M
看代码里，在chunk对象上有个bytes，为什么不清空下？分片上传成功后应该可以释放一些内存了吧

**Comment by dolymood** [comment]
内存增长了并不代表是内存泄漏了

以及chunk上的bytes 当remove掉指定文件的时候 file 连同 chunk 都是会被销毁的

**Comment by sakila1012** [comment]
我这边试了500个100M的文件，测试了火狐浏览器，内存一直累积上升，占用了30多个G，几乎占满了，然后浏览器就闪退了
