### ISSUE TITLE
单文件分片上传

### ISSUE THREAD

**Issue by 15773200610** [simple-uploader/Uploader#85]
只能选择一个文件分片上传，上传完成的可以前端可以从list里面去除掉或者每次重新选择是覆盖而不是追加。请教一下各位大佬，这个要怎么改？？

**Comment by dolymood** [comment]
https://github.com/simple-uploader/Uploader/blob/develop/README_zh-CN.md#%E9%85%8D%E7%BD%AE
singleFile ？
