### ISSUE TITLE
单个分片上传失败，http状态码200，后续分片还在继续上传

### ISSUE THREAD

**Issue by enjoyshuai** [simple-uploader/Uploader#87]
第一个分片上传时，http状态码为200，但是后端返回值还是服务器错误，这种情况下simple-uploader还是根据状态码来判断是否上传成功就不对了吧，有没有可以监听分片上传结束的事件，然后根据接口返回值再来判断是否上传成功，成功再进行后续分片上传，没成功应该修改file的状态码为error吧

**Comment by dolymood** [comment]
processReponse 可以处理
