### ISSUE TITLE
filesAdded 事件，为什么在方法里面return false 还是会继续上传

### ISSUE THREAD

**Issue by superDCH** [simple-uploader/Uploader#88]

**Comment by dolymood** [comment]
如果是 vue 版本 需要设置 ignored = true

**Comment by superDCH** [comment]
大神，可以写在文档里吗？怎么设置ignored呢

**Comment by superDCH** [comment]
打扰了，我知道了呢，
file-added(file), 添加了一个文件事件，一般用做文件校验，如果设置 file.ignored = true 的话这个文件就会被过滤掉。

files-added(files, fileList), 添加了一批文件事件，一般用做一次选择的多个文件进行校验，如果设置 files.ignored = true 或者 fileList.ignored = true 的话本次选择的文件就会被过滤掉。
