### ISSUE TITLE
我想设置个拖拽开始的属性  或者  有没有暴露的标志呢

### ISSUE THREAD

**Issue by Paul-Yellow** [simple-uploader/Uploader#9]

**Comment by dolymood** [comment]
0.3 增加了对应的事件
* `.change(event)` input 的 change 事件。
* `.dragover(event)` 拖拽区域的 dragover 事件。
* `.dragenter(event)` 拖拽区域的 dragenter 事件。
* `.dragleave(event)` 拖拽区域的 dragleave 事件。
